location /public {
    root /data;
}

location /api {
    include api_proxy.conf;
}

location /admin {
    root /app/dist/admin;
    try_files $uri $uri/ /index.html =404;
}

location = /portal {
    absolute_redirect off;
    return 301 /portal/;
}

location /portal/ {
    alias /app/portal/;
    absolute_redirect off;
    index index.html;
    try_files $uri $uri/ /portal/index.html;
}

location /.well-known {
    alias /data/ssl/.well-known;
}

location / {
    root /app/dist;
    try_files $uri $uri/ /index.html =404;
}
