from django.conf.urls import url

from ..views.admin import (AssignRoleAPI, StaffAdminAPI, InstructorListAPI, StaffStatusAPI, StaffDeleteAPI,
                           StaffReissueSabunAPI, StaffHistoryAPI, HRNoticeAdminAPI,
                           LeadDeleteAdminAPI, PrefsAdminAPI,
                           StaffDetailAdminAPI, StaffDocUploadAdminAPI, StaffDocAdminAPI,
                           StaffDocReorderAdminAPI,
                           OptionAdminAPI, OptionReorderAPI, BranchAdminAPI, StudentTimetableAdminAPI,
                           StudentListAdminAPI, StudentWeeklyAdminAPI, TimetableChangeAdminAPI,
                           BulkRegisterAPI, BulkExportAPI,
                           StudentDetailAdminAPI, StudentStatusAdminAPI,
                           StudentGuardianAdminAPI, GuardianSearchAdminAPI, StudentCounselAdminAPI,
                           StudentCredentialAdminAPI,
                           TimetableChangeEditAdminAPI, ClassAdminAPI,
                           ClassEnrollmentAdminAPI, TimetableSlotAdminAPI,
                           ClassSessionAdminAPI, GenerateSessionsAPI,
                           AttendanceAdminAPI, LeadAdminAPI, CounselingNoteAdminAPI,
                           ConvertLeadAdminAPI, CloseLeadAdminAPI, DevLogAdminAPI, ReservationAdminAPI,
                           DashboardAdminAPI, AttendanceCheckAdminAPI, AttendanceNoteAdminAPI,
                           LessonStatusAdminAPI, MakeupAddAdminAPI, TimetableCalendarAPI,
                           LessonEditAdminAPI, PendingMakeupAPI, LessonAbsenceAPI)

urlpatterns = [
    url(r"^academy/staff/?$", StaffAdminAPI.as_view(), name="academy_staff"),
    url(r"^academy/instructors/?$", InstructorListAPI.as_view(), name="academy_instructors"),
    url(r"^academy/staff/status/?$", StaffStatusAPI.as_view(), name="academy_staff_status"),
    url(r"^academy/staff/delete/?$", StaffDeleteAPI.as_view(), name="academy_staff_delete"),
    url(r"^academy/staff/reissue_sabun/?$", StaffReissueSabunAPI.as_view(), name="academy_staff_reissue"),
    url(r"^academy/staff/history/?$", StaffHistoryAPI.as_view(), name="academy_staff_history"),
    url(r"^academy/hr_notices/?$", HRNoticeAdminAPI.as_view(), name="academy_hr_notices"),
    url(r"^academy/staff_detail/?$", StaffDetailAdminAPI.as_view(), name="academy_staff_detail"),
    url(r"^academy/staff_doc/upload/?$", StaffDocUploadAdminAPI.as_view(), name="academy_staff_doc_upload"),
    url(r"^academy/staff_doc/reorder/?$", StaffDocReorderAdminAPI.as_view(), name="academy_staff_doc_reorder"),
    url(r"^academy/staff_doc/?$", StaffDocAdminAPI.as_view(), name="academy_staff_doc"),
    url(r"^academy/options/?$", OptionAdminAPI.as_view(), name="academy_options"),
    url(r"^academy/options/reorder/?$", OptionReorderAPI.as_view(), name="academy_options_reorder"),
    url(r"^academy/branches/?$", BranchAdminAPI.as_view(), name="academy_branches_admin"),
    url(r"^academy/student_timetable/?$", StudentTimetableAdminAPI.as_view(), name="academy_student_timetable"),
    url(r"^academy/students/?$", StudentListAdminAPI.as_view(), name="academy_students"),
    url(r"^academy/bulk_register/?$", BulkRegisterAPI.as_view(), name="academy_bulk_register"),
    url(r"^academy/bulk_export/?$", BulkExportAPI.as_view(), name="academy_bulk_export"),
    url(r"^academy/student_detail/info/?$", StudentDetailAdminAPI.as_view(), name="academy_student_detail_info"),
    url(r"^academy/student_status/?$", StudentStatusAdminAPI.as_view(), name="academy_student_status"),
    url(r"^academy/student_guardian/?$", StudentGuardianAdminAPI.as_view(), name="academy_student_guardian"),
    url(r"^academy/guardian_search/?$", GuardianSearchAdminAPI.as_view(), name="academy_guardian_search"),
    url(r"^academy/student_counsel/?$", StudentCounselAdminAPI.as_view(), name="academy_student_counsel"),
    url(r"^academy/student_credential/?$", StudentCredentialAdminAPI.as_view(), name="academy_student_credential"),
    url(r"^academy/student_weekly/?$", StudentWeeklyAdminAPI.as_view(), name="academy_student_weekly"),
    url(r"^academy/timetable_changes/?$", TimetableChangeAdminAPI.as_view(), name="academy_timetable_changes"),
    url(r"^academy/timetable_change/edit/?$", TimetableChangeEditAdminAPI.as_view(), name="academy_timetable_change_edit"),
    url(r"^academy/lead/?$", LeadAdminAPI.as_view(), name="academy_lead"),
    url(r"^academy/lead/note/?$", CounselingNoteAdminAPI.as_view(), name="academy_lead_note"),
    url(r"^academy/lead/reservation/?$", ReservationAdminAPI.as_view(), name="academy_lead_reservation"),
    url(r"^academy/lead/delete/?$", LeadDeleteAdminAPI.as_view(), name="academy_lead_delete"),
    url(r"^academy/prefs/?$", PrefsAdminAPI.as_view(), name="academy_prefs"),
    url(r"^academy/lead/convert/?$", ConvertLeadAdminAPI.as_view(), name="academy_lead_convert"),
    url(r"^academy/lead/close/?$", CloseLeadAdminAPI.as_view(), name="academy_lead_close"),
    url(r"^academy/assign_role/?$", AssignRoleAPI.as_view(), name="academy_assign_role"),
    url(r"^academy/class/?$", ClassAdminAPI.as_view(), name="academy_class"),
    url(r"^academy/class/enrollment/?$", ClassEnrollmentAdminAPI.as_view(), name="academy_class_enrollment"),
    url(r"^academy/class/timetable/?$", TimetableSlotAdminAPI.as_view(), name="academy_class_timetable"),
    url(r"^academy/session/?$", ClassSessionAdminAPI.as_view(), name="academy_session"),
    url(r"^academy/session/generate/?$", GenerateSessionsAPI.as_view(), name="academy_session_generate"),
    url(r"^academy/attendance/?$", AttendanceAdminAPI.as_view(), name="academy_attendance"),
    url(r"^academy/devlog/?$", DevLogAdminAPI.as_view(), name="academy_devlog"),
    url(r"^academy/dashboard/?$", DashboardAdminAPI.as_view(), name="academy_dashboard"),
    url(r"^academy/attendance_check/?$", AttendanceCheckAdminAPI.as_view(), name="academy_attendance_check"),
    url(r"^academy/attendance_note/?$", AttendanceNoteAdminAPI.as_view(), name="academy_attendance_note"),
    url(r"^academy/lesson_status/?$", LessonStatusAdminAPI.as_view(), name="academy_lesson_status"),
    url(r"^academy/makeup_add/?$", MakeupAddAdminAPI.as_view(), name="academy_makeup_add"),
    url(r"^academy/timetable_calendar/?$", TimetableCalendarAPI.as_view(), name="academy_timetable_calendar"),
    url(r"^academy/lesson_edit/?$", LessonEditAdminAPI.as_view(), name="academy_lesson_edit"),
    url(r"^academy/pending_makeup/?$", PendingMakeupAPI.as_view(), name="academy_pending_makeup"),
    url(r"^academy/lesson_absence/?$", LessonAbsenceAPI.as_view(), name="academy_lesson_absence"),
]
