# Generated by Django 3.2.25 on 2026-08-08 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0059_lessonprogress_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('in_source', models.CharField(blank=True, default='', max_length=16)),
                ('out_source', models.CharField(blank=True, default='', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_attendance', to='academy.branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_staff_attendance',
                'ordering': ['-date', '-id'],
                'unique_together': {('staff', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_from', models.DateField()),
                ('active_until', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('workdays', models.CharField(default='012345', max_length=16)),
                ('break_per_hours', models.PositiveSmallIntegerField(default=4)),
                ('break_minutes', models.PositiveSmallIntegerField(default=30)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='academy.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_work_schedule',
                'ordering': ['-active_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(default='ANNUAL', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_staff_leave',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendanceChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=16)),
                ('old_value', models.CharField(blank=True, default='', max_length=64)),
                ('new_value', models.CharField(blank=True, default='', max_length=64)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='DIRECT', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=16)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='academy.staffattendance')),
            ],
            options={
                'db_table': 'academy_staff_attendance_change',
                'ordering': ['-create_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=64)),
                ('kind', models.CharField(default='PUBLIC', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='academy.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_holiday',
                'ordering': ['date', 'id'],
            },
        ),
    ]
