# Generated by Django 3.2.25 on 2026-08-09 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0060_hr_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, db_index=True, default='', max_length=48)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='SENT', max_length=16)),
                ('staff_snapshot', models.TextField(blank=True, default='')),
                ('parent_data', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_data', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_profile_verification',
                'ordering': ['-create_time', '-id'],
            },
        ),
    ]
