# Generated by Django 3.2.25 on 2026-08-11 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0061_profileverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='CERT', max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('organizer', models.CharField(blank=True, default='', max_length=64)),
                ('homepage', models.CharField(blank=True, default='', max_length=255)),
                ('entry_mode', models.CharField(default='INDIVIDUAL', max_length=16)),
                ('fee', models.PositiveIntegerField(blank=True, null=True)),
                ('levels', models.TextField(blank=True, default='')),
                ('tracks', models.TextField(blank=True, default='')),
                ('annual', models.BooleanField(default=False)),
                ('check_from', models.CharField(blank=True, default='', max_length=8)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_catalogs', to='academy.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_exam_catalog',
                'ordering': ['kind', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='CERT', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('apply_from', models.DateField(blank=True, null=True)),
                ('apply_until', models.DateField(blank=True, null=True)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('entry_mode', models.CharField(blank=True, default='', max_length=16)),
                ('place', models.CharField(blank=True, default='', max_length=128)),
                ('fee', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('confirmed', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='academy.branch')),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='academy.examcatalog')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_exam_session',
                'ordering': ['-exam_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExamTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='academy.examsession')),
            ],
            options={
                'db_table': 'academy_exam_team',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, default='', max_length=16)),
                ('track', models.CharField(blank=True, default='', max_length=32)),
                ('applied', models.BooleanField(default=False)),
                ('applied_at', models.DateField(blank=True, null=True)),
                ('fee_paid', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, default='', max_length=32)),
                ('score', models.CharField(blank=True, default='', max_length=32)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='academy.examcatalog')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academy.studentcredential')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='academy.examsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_entries', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='academy.examteam')),
            ],
            options={
                'db_table': 'academy_exam_entry',
                'ordering': ['-id'],
            },
        ),
    ]
