# Generated by Django 3.2.25 on 2026-08-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0062_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcatalog',
            name='apply_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='examcatalog',
            name='notice_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
