# Generated by Django 3.2.25 on 2026-08-12 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0063_exam_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='examentry',
            name='stage',
            field=models.CharField(default='CANDIDATE', max_length=16),
        ),
        migrations.CreateModel(
            name='ExamContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='APPLY_GUIDE', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='academy.examentry')),
            ],
            options={
                'db_table': 'academy_exam_contact',
                'ordering': ['-create_time', '-id'],
            },
        ),
    ]
