# Generated by Django 3.2.25 on 2026-08-12 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0064_exam_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('roles', models.TextField(blank=True, default='')),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academy_menu_setting',
            },
        ),
        migrations.CreateModel(
            name='MenuOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('allow', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_menu_override',
                'unique_together': {('staff', 'key')},
            },
        ),
    ]
