# Generated by Django 3.2.25 on 2026-08-12 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0065_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusetting',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_settings', to='academy.branch'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='key',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='menusetting',
            unique_together={('key', 'branch')},
        ),
    ]
