# Generated by Django 3.2.25 on 2026-08-12 05:32

from django.db import migrations, models

# 사람이 직접 쓰는 비고·사유가 255자를 넘으면 저장이 통째로 실패했다(서버 오류).
# 수업 비고에 여러 줄짜리 보강 계획을 적다 걸린 것. 길이를 재지 않게 바꾼다.


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0066_menu_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancechange',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='memo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='counselreservation',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='examcatalog',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='examcontact',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='examentry',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='examteam',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lessonoccurrence',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='staffattendancechange',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='staffchangelog',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='staffleave',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentstatuschange',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='timetablechange',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
