# Generated by Django 3.2.25 on 2026-08-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0067_long_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcatalog',
            name='rounds',
            field=models.TextField(blank=True, default=''),
        ),
    ]
