# Generated by Django 3.2.25 on 2026-08-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0068_exam_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcatalog',
            name='venues',
            field=models.TextField(blank=True, default=''),
        ),
    ]
