# Generated by Django 3.2.25 on 2026-08-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0069_exam_venues'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='level',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='examsession',
            name='round',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='examsession',
            name='track',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
