# Generated by Django 3.2.25 on 2026-08-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0070_session_level_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='examentry',
            name='apply_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examentry',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examentry',
            name='place',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='examentry',
            name='result_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examentry',
            name='round',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
