# Generated by Django 3.2.25 on 2026-08-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0071_entry_own_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='examentry',
            name='exam_time',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='examsession',
            name='exam_time',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
