# Generated by Django 3.2.25 on 2026-08-12 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0072_exam_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='examentry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examentry',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examentry',
            name='deleted_reason',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='ExamChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='CREATE', max_length=16)),
                ('exam_kind', models.CharField(blank=True, default='', max_length=16)),
                ('label', models.CharField(blank=True, default='', max_length=160)),
                ('detail', models.TextField(blank=True, default='')),
                ('entry_count', models.PositiveSmallIntegerField(default=0)),
                ('students', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academy.branch')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='academy.examsession')),
            ],
            options={
                'db_table': 'academy_exam_change',
                'ordering': ['-id'],
            },
        ),
    ]
