# Generated by Django 3.2.25 on 2026-08-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0073_exam_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='submit_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
