# Generated by Django 3.2.25 on 2026-08-12 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0074_submit_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayOptOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_opt_outs', to='academy.branch')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt_outs', to='academy.holiday')),
            ],
            options={
                'db_table': 'academy_holiday_optout',
                'unique_together': {('holiday', 'branch')},
            },
        ),
    ]
