# Generated by Django 3.2.25 on 2026-08-12 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0075_holiday_optout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='phone', max_length=32)),
                ('query', models.CharField(max_length=200)),
                ('is_favorite', models.BooleanField(default=False)),
                ('use_count', models.PositiveIntegerField(default=1)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_saved_search',
                'ordering': ['-is_favorite', '-last_used_at'],
                'unique_together': {('user', 'scope', 'query')},
            },
        ),
    ]
