# Generated by Django 3.2.25 on 2026-08-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0076_saved_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='prev_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
