# Generated by Django 3.2.25 on 2026-08-13 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0077_prev_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='prev_link',
        ),
    ]
