# Generated by Django 3.2.25 on 2026-08-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0078_drop_prev_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='consent_paper',
            field=models.BooleanField(default=False),
        ),
    ]
