# Generated by Django 3.2.25 on 2026-08-13 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0079_consent_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='SPRING', max_length=8)),
                ('school_year', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True, default='')),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='academy.branch')),
                ('undone_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_promotion_batch',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PromotionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_school_type', models.CharField(blank=True, default='', max_length=16)),
                ('old_school_name', models.CharField(blank=True, default='', max_length=64)),
                ('old_grade', models.CharField(blank=True, default='', max_length=8)),
                ('new_school_type', models.CharField(blank=True, default='', max_length=16)),
                ('new_school_name', models.CharField(blank=True, default='', max_length=64)),
                ('new_grade', models.CharField(blank=True, default='', max_length=8)),
                ('action', models.CharField(blank=True, default='', max_length=16)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academy.promotionbatch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_promotion_item',
            },
        ),
    ]
