# Generated by Django 3.2.25 on 2026-08-13 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0080_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='academyprofile',
            name='hourly_wage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academyprofile',
            name='work_type',
            field=models.CharField(default='FIXED', max_length=16),
        ),
        migrations.CreateModel(
            name='StaffWorkPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('note', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_staff_work_plan',
                'ordering': ['date'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
