# Generated by Django 3.2.25 on 2026-08-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0081_work_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='waived_docs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
