# Generated by Django 3.2.25 on 2026-08-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0082_waived_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofilehistory',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
