# Generated by Django 3.2.25 on 2026-08-13 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0083_hr_history_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlanChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('old_start', models.CharField(blank=True, default='', max_length=5)),
                ('old_end', models.CharField(blank=True, default='', max_length=5)),
                ('new_start', models.CharField(blank=True, default='', max_length=5)),
                ('new_end', models.CharField(blank=True, default='', max_length=5)),
                ('note', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_plan_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_work_plan_change',
                'ordering': ['-id'],
            },
        ),
    ]
