# Generated by Django 3.2.25 on 2026-08-13 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0084_work_plan_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegisterLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='DIRECT', max_length=16)),
                ('batch', models.CharField(blank=True, default='', max_length=40)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academy.branch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_student_register_log',
                'ordering': ['-id'],
            },
        ),
    ]
