# Generated by Django 3.2.25 on 2026-08-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0085_student_register_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='counsel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
