# Generated by Django 3.2.25 on 2026-08-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0086_lead_counsel_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='channel',
            field=models.CharField(blank=True, default='VISIT', max_length=16),
        ),
    ]
