# Generated by Django 3.2.25 on 2026-08-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0087_lead_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_until_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
