# Generated by Django 3.2.25 on 2026-08-14 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0088_enrollment_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionRateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academy.branch')),
            ],
            options={
                'db_table': 'academy_tuition_rate_change',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DiscountItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('kind', models.CharField(default='AMOUNT', max_length=16)),
                ('value', models.PositiveIntegerField(default=0)),
                ('recurring', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_items', to='academy.branch')),
            ],
            options={
                'db_table': 'academy_discount_item',
                'ordering': ['branch_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TuitionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_per_week', models.PositiveSmallIntegerField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_rates', to='academy.branch')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_tuition_rate',
                'ordering': ['branch_id', 'sessions_per_week', 'duration_minutes'],
                'unique_together': {('branch', 'sessions_per_week', 'duration_minutes')},
            },
        ),
    ]
