# Generated by Django 3.2.25 on 2026-08-18 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0090_student_tuition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(max_length=7)),
                ('base_amount', models.PositiveIntegerField(default=0)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('lines', models.TextField(blank=True, default='')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('is_void', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='academy.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_invoice',
                'ordering': ['-ym', 'student_id'],
                'unique_together': {('student', 'ym')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_on', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('method', models.CharField(default='TRANSFER', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('is_void', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academy.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_payment',
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAlloc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocs', to='academy.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocs', to='academy.payment')),
            ],
            options={
                'db_table': 'academy_payment_alloc',
            },
        ),
    ]
