# Generated by Django 3.2.25 on 2026-08-18 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0091_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-ym', 'student_id', '-revision']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='revision',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('student', 'ym', 'revision')},
        ),
    ]
