# Generated by Django 3.2.25 on 2026-08-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0092_invoice_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdiscount',
            name='used_ym',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
