# Generated by Django 3.2.25 on 2026-08-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0093_discount_used_ym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='enrollment_until',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='enrollment_until_note',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pending_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pending_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pending_status',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
