# Generated by Django 3.2.25 on 2026-08-20 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0094_pending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='discount_cap_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='discount_cap_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_session_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discountitem',
            name='exclude_from_cap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discountitem',
            name='once_per_month',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='value_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='referred_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='referrer_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
