# Generated by Django 3.2.25 on 2026-08-20 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0095_auto_20260820_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.CharField(blank=True, default='', max_length=8)),
                ('scope', models.CharField(default='ALL', max_length=16)),
                ('need_read', models.BooleanField(default=False)),
                ('sort_mode', models.CharField(default='RECENT', max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_folders', to='academy.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='academy.boardfolder')),
            ],
            options={
                'db_table': 'academy_board_folder',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BoardPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('is_pinned', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='academy.boardfolder')),
                ('students', models.ManyToManyField(blank=True, related_name='board_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_board_post',
                'ordering': ['-is_pinned', 'order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BoardFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('thumb_url', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(blank=True, default='', max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='academy.boardpost')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_board_file',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BoardRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='academy.boardpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_board_read',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
