# Generated by Django 3.2.25 on 2026-08-20 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0096_boardfile_boardfolder_boardpost_boardread'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardfolder',
            name='versioned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BoardPostVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('files', models.TextField(blank=True, default='')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='academy.boardpost')),
            ],
            options={
                'db_table': 'academy_board_post_version',
                'ordering': ['-rev'],
                'unique_together': {('post', 'rev')},
            },
        ),
    ]
