# Generated by Django 3.2.25 on 2026-08-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0099_auto_20260820_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardfolder',
            name='pin_when_collapsed',
            field=models.BooleanField(default=False),
        ),
    ]
