# Generated by Django 3.2.25 on 2026-08-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0102_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardfolder',
            name='read_floor',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
