# Generated by Django 3.2.25 on 2026-08-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0103_boardfolder_read_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonoccurrence',
            name='extra_reason',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='lessonoccurrence',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
    ]
