# Generated by Django 3.2.25 on 2026-08-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0104_auto_20260828_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountitem',
            old_name='exclude_from_cap',
            new_name='stands_alone',
        ),
        migrations.AddField(
            model_name='discountitem',
            name='cap_scope',
            field=models.CharField(default='DEFAULT', max_length=16),
        ),
        migrations.CreateModel(
            name='DiscountCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='DEFAULT', max_length=16)),
                ('sessions_min', models.PositiveIntegerField(default=0)),
                ('months_min', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_caps', to='academy.branch')),
            ],
            options={
                'db_table': 'academy_discount_cap',
                'ordering': ['branch_id', 'scope', '-sessions_min', '-months_min'],
            },
        ),
    ]
