# Generated by Django 3.2.25 on 2026-09-03 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0105_auto_20260828_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_name', models.CharField(blank=True, default='', max_length=64)),
                ('to_phone', models.CharField(blank=True, default='', max_length=32)),
                ('kind', models.CharField(default='ETC', max_length=16)),
                ('channel', models.CharField(blank=True, default='', max_length=16)),
                ('provider', models.CharField(blank=True, default='', max_length=16)),
                ('template_code', models.CharField(blank=True, default='', max_length=64)),
                ('body', models.TextField(blank=True, default='')),
                ('variables', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('provider_msg_id', models.CharField(blank=True, default='', max_length=64)),
                ('idem_key', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('ref_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_logs', to='academy.branch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_notify_log',
                'ordering': ['-create_time', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='notifylog',
            index=models.Index(fields=['student', '-create_time'], name='academy_not_student_161cf1_idx'),
        ),
    ]
