# Generated by Django 3.2.25 on 2026-09-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0106_auto_20260903_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdiscount',
            name='stands_alone_override',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
